---
driver:
  name: vagrant
  provider: hyperv
  network:
  - ["public_network", {bridge: "ExternalNAT"}]

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012R2
    transport:
      name: winrm
    driver:
      guest: :windows
      box: Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[dsc_nugetserver::default]
    attributes:
